# Data source
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bbdd_proyecto}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

server.port=${SERVER_PORT:8082}

# JPA / Hibernate
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

# Upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Execution mode
execution.mode=${EXECUTION_MODE:0}

# Messages
spring.messages.cache-duration=3600
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Servlet encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Mail
mailstrap.username=${MAILSTRAP_USERNAME:}
mailstrap.password=${MAILSTRAP_PASSWORD:}
mailstrap.host=${MAILSTRAP_HOST:live.smtp.mailtrap.io}
mailstrap.props_mail_smtp_auth=${MAILSTRAP_SMTP_AUTH:true}
mailstrap.props_mail_smtp_starttls_enable=${MAILSTRAP_STARTTLS:true}
mailstrap.props_mail_smtp_host=${MAILSTRAP_SMTP_HOST:host}
mailstrap.props_mail_smtp_port=${MAILSTRAP_SMTP_PORT:587}
mailstrap.props_smtp.auth=${MAILSTRAP_PROPS_SMTP_AUTH:true}